# Generated by Django 2.2.5 on 2019-10-17 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beds', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roomType', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('lng', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maxGuests', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('details', models.CharField(max_length=500)),
                ('imgUrl', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('properties', models.ManyToManyField(related_name='properties', through='main.Booking', to='main.Property')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main.Property'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main.User'),
        ),
    ]
