# Generated by Django 2.2.5 on 2019-10-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lat',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='property',
            name='lng',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
