# Generated by Django 2.2.6 on 2020-08-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel',
            field=models.BooleanField(null=True),
        ),
    ]
