# Generated by Django 2.2.6 on 2020-08-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
